package com.fpt.edu.vn.smart_map.service;

import com.fpt.edu.vn.smart_map.dto.StationDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Sinh mã C++ (header) cho ESP32 từ danh sách trạm đã gắn trên một bản đồ.
 *
 * <p>Output gồm 2 mảng song song (cùng index → cùng trạm):
 * <ul>
 *   <li><b>cac_tram[]</b>: struct <code>ToaDoMain { int x; int y; }</code> —
 *       index 0 là gốc tọa độ <code>{0, 0}</code> ứng với "Không xác định".</li>
 *   <li><b>ten_tram[]</b>: <code>const char*</code> tên trạm tương ứng.</li>
 * </ul>
 *
 * <p>Ví dụ output với 4 trạm:
 * <pre>
 * ToaDoMain cac_tram[] = {
 *     {0, 0},
 *     {34, 58},   // Trạm 1: Cửa Số 1
 *     {10, 112},  // Trạm 2: IT
 *     {142, 161}, // Trạm 3: Thư viện
 *     {220, 61}   // Trạm 4: WC
 * };
 * const char *ten_tram[] = {"Không xác định", "Cửa Số 1", "Phòng IT", "Thư Viện", "Nhà WC"};
 * </pre>
 *
 * <p>Sắp xếp theo <code>id ASC</code> để diff ổn định qua các lần generate.</p>
 */
@Service
@Slf4j
public class CodeGeneratorService {

    private static final DateTimeFormatter ISO_UTC = DateTimeFormatter
            .ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'")
            .withZone(ZoneOffset.UTC);

    /**
     * Sinh header C++ cho ESP32 từ danh sách trạm.
     *
     * @param mapId      id bản đồ (chỉ để ghi vào comment)
     * @param mapName    tên bản đồ (chỉ để ghi vào comment)
     * @param stations   danh sách trạm; trạm null/lỗi sẽ bị bỏ qua
     * @return chuỗi C++ hoàn chỉnh, có trailing newline
     */
    public String generate(Long mapId, String mapName, List<StationDto.Response> stations) {
        StringBuilder sb = new StringBuilder(512);

        // ----- Header comment ------------------------------------------------
        sb.append("// ============================================================\n")
          .append("// AUTO-GENERATED by Smart Map Admin Console.\n")
          .append("// Do NOT edit manually — regenerate from the web UI.\n")
          .append("// Generated at: ").append(ISO_UTC.format(Instant.now())).append("\n");

        if (mapId != null) {
            sb.append("// Map ID   : ").append(mapId).append("\n");
        }
        if (mapName != null && !mapName.isBlank()) {
            sb.append("// Map Name : ").append(mapName).append("\n");
        }

        // Sắp xếp theo id ASC để diff ổn định.
        List<StationDto.Response> sorted = stations.stream()
                .filter(s -> s != null && s.getId() != null)
                .sorted((a, b) -> Long.compare(a.getId(), b.getId()))
                .toList();

        sb.append("// Stations : ").append(sorted.size()).append("\n");

        long lostCount = sorted.stream()
                .filter(s -> "LOST".equalsIgnoreCase(s.getStatus()))
                .count();
        if (lostCount > 0) {
            sb.append("// WARNING  : ").append(lostCount)
              .append(" station(s) marked LOST — verify before flashing.\n");
        }
        sb.append("// ============================================================\n\n");

        // ----- Count constant ----------------------------------------------
        // Tổng phần tử = 1 (gốc {0,0}) + số trạm thực tế.
        int total = sorted.size() + 1;
        sb.append("const int SO_LUONG_TRAM = ").append(total).append(";\n\n");

        // ----- Struct ToaDoMain (2D: chỉ x, y) -----------------------------
        sb.append("struct ToaDoMain {\n")
          .append("    int x;\n")
          .append("    int y;\n")
          .append("};\n\n");

        // ----- Array literal: cac_tram[] ------------------------------------
        sb.append("ToaDoMain cac_tram[SO_LUONG_TRAM] = {\n");
        // Index 0: gốc tọa độ
        sb.append("    {0, 0},                  // Index 0: Không xác định\n");
        // Index 1..N: trạm thực tế
        if (sorted.isEmpty()) {
            sb.append("    // (không có trạm nào trên bản đồ này)\n");
        } else {
            for (int i = 0; i < sorted.size(); i++) {
                StationDto.Response s = sorted.get(i);
                int index = i + 1;
                sb.append("    {")
                  .append(roundToInt(s.getCoordX())).append(", ")
                  .append(roundToInt(s.getCoordY())).append("},   ")
                  .append("// Trạm ").append(index).append(": ")
                  .append(escape(s.getName())).append("\n");
            }
        }
        sb.append("};\n\n");

        // ----- Array literal: ten_tram[] ------------------------------------
        sb.append("const char *ten_tram[SO_LUONG_TRAM] = {\n");
        sb.append("    \"Không xác định\"");
        for (StationDto.Response s : sorted) {
            sb.append(",\n    ").append(quote(escape(s.getName())));
        }
        sb.append("\n};\n");

        log.info("Generated C++ config: mapId={} stationCount={} lostCount={}",
                mapId, sorted.size(), lostCount);
        return sb.toString();
    }

    // ----- Helpers ----------------------------------------------------------

    /** Làm tròn double về int (coi 250.7 → 251). Trả 0 nếu null/NaN. */
    private int roundToInt(Double v) {
        if (v == null || v.isNaN() || v.isInfinite()) return 0;
        return (int) Math.round(v);
    }

    /** Escape ký tự đặc biệt trong string C: backslash và dấu nháy. */
    private String escape(String s) {
        if (s == null) return "";
        StringBuilder out = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\' || c == '"') out.append('\\').append(c);
            else if (c == '\n') out.append("\\n");
            else if (c == '\r') out.append("\\r");
            else if (c == '\t') out.append("\\t");
            else out.append(c);
        }
        return out.toString();
    }

    private String quote(String s) {
        return "\"" + s + "\"";
    }
}