package com.fpt.edu.vn.smart_map.service;

import com.fpt.edu.vn.smart_map.dto.StationDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Sinh mã C++ (header) cho ESP32 từ danh sách trạm đã gắn trên một bản đồ.
 *
 * <p>Output được chèn thẳng vào <code>main.cpp</code> của thiết bị, dùng làm
 * bảng tra cứu tọa độ + MAC của các trạm phát. Định dạng đầu ra ổn định —
 * byte-for-byte diff chỉ phụ thuộc vào dữ liệu DB (không có timestamp,
 * không có UUID).</p>
 *
 * <p>Quy ước:
 * <ul>
 *   <li>Struct <code>ToaDoMain</code>: id (int), name (const char*), x (int), y (int), mac (const char*)</li>
 *   <li>Sắp xếp theo <code>id ASC</code> để output ổn định qua các lần generate.</li>
 *   <li>Cảnh báo trong comment header nếu có trạm <code>LOST</code>.</li>
 * </ul>
 */
@Service
@Slf4j
public class CodeGeneratorService {

    private static final DateTimeFormatter ISO_UTC = DateTimeFormatter
            .ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'")
            .withZone(ZoneOffset.UTC);

    /**
     * Sinh header C++ cho ESP32 từ danh sách trạm.
     *
     * @param mapId      id bản đồ (chỉ để ghi vào comment)
     * @param mapName    tên bản đồ (chỉ để ghi vào comment)
     * @param stations   danh sách trạm; trạm null/lỗi sẽ bị bỏ qua
     * @return chuỗi C++ hoàn chỉnh, có trailing newline
     */
    public String generate(Long mapId, String mapName, List<StationDto.Response> stations) {
        StringBuilder sb = new StringBuilder(512);

        // ----- Header comment ------------------------------------------------
        sb.append("// ============================================================\n")
          .append("// AUTO-GENERATED by Smart Map Admin Console.\n")
          .append("// Do NOT edit manually — regenerate from the web UI.\n")
          .append("// Generated at: ").append(ISO_UTC.format(Instant.now())).append("\n");

        if (mapId != null) {
            sb.append("// Map ID   : ").append(mapId).append("\n");
        }
        if (mapName != null && !mapName.isBlank()) {
            sb.append("// Map Name : ").append(mapName).append("\n");
        }

        // Sắp xếp theo id ASC để diff ổn định.
        List<StationDto.Response> sorted = stations.stream()
                .filter(s -> s != null && s.getId() != null)
                .sorted((a, b) -> Long.compare(a.getId(), b.getId()))
                .toList();

        sb.append("// Stations : ").append(sorted.size()).append("\n");

        long lostCount = sorted.stream()
                .filter(s -> "LOST".equalsIgnoreCase(s.getStatus()))
                .count();
        if (lostCount > 0) {
            sb.append("// WARNING  : ").append(lostCount)
              .append(" station(s) marked LOST — verify before flashing.\n");
        }
        sb.append("// ============================================================\n\n");

        // ----- Count constant ----------------------------------------------
        sb.append("const int SO_LUONG_TRAM = ").append(sorted.size()).append(";\n\n");

        // ----- Struct ToaDoMain ---------------------------------------------
        sb.append("struct ToaDoMain {\n")
          .append("    int id;\n")
          .append("    const char* name;\n")
          .append("    int x;\n")
          .append("    int y;\n")
          .append("    const char* mac;\n")
          .append("};\n\n");

        // ----- Array literal ------------------------------------------------
        sb.append("ToaDoMain cac_tram[SO_LUONG_TRAM] = {\n");
        if (sorted.isEmpty()) {
            sb.append("    // (no stations on this map)\n");
        } else {
            sb.append("    // { id, name, x, y, mac }\n");
            for (StationDto.Response s : sorted) {
                sb.append("    {")
                  .append(s.getId()).append(", ")
                  .append(quote(escape(s.getName()))).append(", ")
                  .append(roundToInt(s.getCoordX())).append(", ")
                  .append(roundToInt(s.getCoordY())).append(", ")
                  .append(quote(escape(s.getMacAddress())))
                  .append(" },\n");
            }
        }
        sb.append("};\n");

        log.info("Generated C++ config: mapId={} stationCount={} lostCount={}",
                mapId, sorted.size(), lostCount);
        return sb.toString();
    }

    // ----- Helpers ----------------------------------------------------------

    /** Làm tròn double về int (coi 250.7 → 251). Trả 0 nếu null/NaN. */
    private int roundToInt(Double v) {
        if (v == null || v.isNaN() || v.isInfinite()) return 0;
        return (int) Math.round(v);
    }

    /** Escape ký tự đặc biệt trong string C: backslash và dấu nháy. */
    private String escape(String s) {
        if (s == null) return "";
        StringBuilder out = new StringBuilder(s.length());
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\' || c == '"') out.append('\\').append(c);
            else if (c == '\n') out.append("\\n");
            else if (c == '\r') out.append("\\r");
            else if (c == '\t') out.append("\\t");
            else out.append(c);
        }
        return out.toString();
    }

    private String quote(String s) {
        return "\"" + s + "\"";
    }
}